# **k-Fold Cross Validation & Grid Search**
## **Data Preprocessing**

### **Importing the libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

### **Loading the data set**

In [2]:
df = pd.read_csv('../input/personal-key-indicators-of-heart-disease/heart_2020_cleaned.csv')
df.head()

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No             3.0   
1           No  20.34      No              No    Yes             0.0   
2           No  26.58     Yes              No     No            20.0   
3           No  24.21      No              No     No             0.0   
4           No  23.71      No              No     No            28.0   

   MentalHealth DiffWalking     Sex  AgeCategory   Race Diabetic  \
0          30.0          No  Female        55-59  White      Yes   
1           0.0          No  Female  80 or older  White       No   
2          30.0          No    Male        65-69  White      Yes   
3           0.0          No  Female        75-79  White       No   
4           0.0         Yes  Female        40-44  White       No   

  PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0              Yes  Very good        5.0    Yes            No        Yes  
1              Yes  Very good        7.0     No            No         No  
2              Yes       Fair        8.0    Yes            No         No  
3               No       Good        6.0     No            No        Yes  
4              Yes  Very good        8.0     No            No         No

In [3]:
df['AgeCategory'].value_counts()

65-69          34151
60-64          33686
70-74          31065
55-59          29757
50-54          25382
80 or older    24153
45-49          21791
75-79          21482
18-24          21064
40-44          21006
35-39          20550
30-34          18753
25-29          16955
Name: AgeCategory, dtype: int64

In [4]:
#Label Encoding 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Smoking'] = le.fit_transform(df['Smoking'])
df['AlcoholDrinking'] = le.fit_transform(df['AlcoholDrinking'])
df['Stroke'] = le.fit_transform(df['Stroke'])
df['DiffWalking'] = le.fit_transform(df['DiffWalking'])
df['Sex'] = le.fit_transform(df['Sex'])
df['Diabetic'] = le.fit_transform(df['Diabetic'])
df['PhysicalActivity'] = le.fit_transform(df['PhysicalActivity'])
df['Asthma'] = le.fit_transform(df['Asthma'])
df['KidneyDisease'] = le.fit_transform(df['KidneyDisease'])
df['SkinCancer'] = le.fit_transform(df['SkinCancer'])

Race = pd.get_dummies(df['Race'],drop_first=True)
GenHealth = pd.get_dummies(df['GenHealth'],drop_first=True)
AgeCategory = pd.get_dummies(df['AgeCategory'],drop_first=True)
df = pd.concat([df,Race, GenHealth, AgeCategory],axis=1)
df.drop(['Race', 'GenHealth', 'AgeCategory'],axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 36 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   HeartDisease      319795 non-null  object 
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  int64  
 3   AlcoholDrinking   319795 non-null  int64  
 4   Stroke            319795 non-null  int64  
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  int64  
 8   Sex               319795 non-null  int64  
 9   Diabetic          319795 non-null  int64  
 10  PhysicalActivity  319795 non-null  int64  
 11  SleepTime         319795 non-null  float64
 12  Asthma            319795 non-null  int64  
 13  KidneyDisease     319795 non-null  int64  
 14  SkinCancer        319795 non-null  int64  
 15  Asian             319795 non-null  uint8  
 16  Black             31

In [5]:
from sklearn.model_selection import train_test_split
X = df.drop('HeartDisease',axis=1)
y = df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
clf1 = LogisticRegression(max_iter =10000)
clf2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
clf3 = SVC(kernel = 'rbf',  gamma=0.5, C=1, random_state = 0)
clf4 = GaussianNB()
clf5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf6 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
clf1 = LogisticRegression(max_iter =10000)
clf2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
#clf3 = SVC(kernel = 'rbf',  gamma=0.5, C=1, random_state = 0)
clf4 = GaussianNB()
clf5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf6 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

#Training the Classification models on the Train set
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
#clf3.fit(X_train, y_train)
clf4.fit(X_train, y_train)
clf5.fit(X_train, y_train)
clf6.fit(X_train, y_train)

#Predicting the Test set results
y_pred_LR = clf1.predict(X_test)
y_pred_KNN = clf2.predict(X_test)
#y_pred_SVC = clf3.predict(X_test)
y_pred_NB = clf4.predict(X_test)
y_pred_DTC = clf5.predict(X_test)
y_pred_RFC = clf6.predict(X_test)

#KEY PERFORMANCE INDICATORS (KPI)
#Generating the Confusion Matrix and Classification report
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
print('Accuracy of Logistic Regression Model is ', accuracy_score(y_test, y_pred_LR))
print('\n','Confusion Matrix of Logistic Regression Model:' '\n', confusion_matrix(y_test, y_pred_LR))
print('\n', '\n','Classification Report for Logistic Regression Model:' '\n',classification_report(y_test, y_pred_LR))
print('\n','\n','Accuracy of K-Nearest Neighbor Model is ', accuracy_score(y_test, y_pred_KNN))
print('\n','Confusion Matrix of K-Nearest Neighbor Model:' '\n', confusion_matrix(y_test, y_pred_KNN))
print('\n', '\n','Classification Report for K-Nearest Neighbor Model:' '\n',classification_report(y_test, y_pred_KNN))
#print('\n','\n', 'Accuracy of Support Vector Classification Model is ', accuracy_score(y_test, y_pred_SVC))
#print('\n','Confusion Matrix of Support Vector Classification Model:' '\n', confusion_matrix(y_test, y_pred_SVC))
#print('\n', '\n','Classification Report for Support Vector Classification Model:' '\n',classification_report(y_test, y_pred_SVC))
print('\n','\n', 'Accuracy of Naive Bayes Classification  Model is ', accuracy_score(y_test, y_pred_NB))
print('\n','Confusion Matrix of Naive Bayes Classification  Model:' '\n', confusion_matrix(y_test, y_pred_NB))
print('\n', '\n','Classification Report for Naive Bayes Classification  Model:' '\n',classification_report(y_test, y_pred_NB))
print('\n','\n', 'Accuracy of Decision Tree Model is ', accuracy_score(y_test, y_pred_DTC))
print('\n','Confusion Matrix of Decision Tree Model:' '\n', confusion_matrix(y_test, y_pred_DTC))
print('\n', '\n','Classification Report for Decision Tree Model:' '\n',classification_report(y_test, y_pred_DTC))
print('\n','\n', 'Accuracy of Random Forest Model is ', accuracy_score(y_test, y_pred_RFC))
print('\n','Confusion Matrix of  Random Forest Model:' '\n', confusion_matrix(y_test, y_pred_RFC))
print('\n', '\n','Classification Report for  Random Forest Model:' '\n',classification_report(y_test, y_pred_RFC))

Accuracy of Logistic Regression Model is  0.9156338923691095

 Confusion Matrix of Logistic Regression Model:
 [[86958   727]
 [ 7367   887]]

 
 Classification Report for Logistic Regression Model:
               precision    recall  f1-score   support

          No       0.92      0.99      0.96     87685
         Yes       0.55      0.11      0.18      8254

    accuracy                           0.92     95939
   macro avg       0.74      0.55      0.57     95939
weighted avg       0.89      0.92      0.89     95939


 
 Accuracy of K-Nearest Neighbor Model is  0.906857482358582

 Confusion Matrix of K-Nearest Neighbor Model:
 [[86357  1328]
 [ 7608   646]]

 
 Classification Report for K-Nearest Neighbor Model:
               precision    recall  f1-score   support

          No       0.92      0.98      0.95     87685
         Yes       0.33      0.08      0.13      8254

    accuracy                           0.91     95939
   macro avg       0.62      0.53      0.54     95939
w

## **k-Fold Cross Validation**

In [8]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score


accuracies_LR = cross_val_score(estimator = clf1, X = X_train, y = y_train, cv = 10)
print("Accuracy  of Logistic Regression Model: {:.2f} %".format(accuracies_LR.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_LR.std()*100))

accuracies_KNN = cross_val_score(estimator = clf2, X = X_train, y = y_train, cv = 10)
print("Accuracy  of K-Nearest Neighbor Model: {:.2f} %".format(accuracies_KNN.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_KNN.std()*100))

#accuracies_SV = cross_val_score(estimator = clf3, X = X_train, y = y_train, cv = 10)
#print("Accuracy  of Support Vector Model: {:.2f} %".format(accuracies_SV.mean()*100))
#print("Standard Deviation: {:.2f} %".format(accuracies_SV.std()*100))

accuracies_NB = cross_val_score(estimator = clf4, X = X_train, y = y_train, cv = 10)
print("Accuracy  of Naive Bayes Model: {:.2f} %".format(accuracies_NB.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_NB.std()*100))

accuracies_DTC = cross_val_score(estimator = clf5, X = X_train, y = y_train, cv = 10)
print("Accuracy  of Decision Tree Model: {:.2f} %".format(accuracies_DTC.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_DTC.std()*100))

accuracies_RF = cross_val_score(estimator = clf6, X = X_train, y = y_train, cv = 10)
print("Accuracy  of Random Forest Model: {:.2f} %".format(accuracies_RF.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies_RF.std()*100))

Accuracy  of Logistic Regression Model: 91.59 %
Standard Deviation: 0.09 %
Accuracy  of K-Nearest Neighbor Model: 90.75 %
Standard Deviation: 0.12 %
Accuracy  of Naive Bayes Model: 74.45 %
Standard Deviation: 0.31 %
Accuracy  of Decision Tree Model: 86.62 %
Standard Deviation: 0.17 %
Accuracy  of Random Forest Model: 90.46 %
Standard Deviation: 0.10 %


## **GridSearchCV**

GridSearchCV is a module of the Sklearn model_selection package that is used for Hyperparameter tuning. Given a set of different hyperparameters, GridSearchCV loops through all possible values and combinations of the hyperparameter and fits the model on the training dataset. In this process, it is able to identify the best values and combination of hyperparameters (from the given set) that produces the best accuracy.

### **Logistic Regression with GridSearchCV**

In [9]:
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
grid_values = {'penalty': ['l1','l2'], 'C': [0.001,0.01,0.1,1,10,100,1000]}
grid_search = GridSearchCV(clf1, param_grid=grid_values)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy of Logistic Regression Model: {:.2f} %".format(best_accuracy*100))
print("Best Parameters of Logistic Regression Model:", best_parameters)


/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 70.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver

Best Accuracy of Logistic Regression Model: 91.62 %
Best Parameters of Logistic Regression Model: {'C': 0.01, 'penalty': 'l2'}


### **KNN with GridSearchCV**

In [10]:
k_range = list(range(1, 7))
param_grid = dict(n_neighbors=k_range)
grid_knn = GridSearchCV(clf2, param_grid, cv=5, scoring='accuracy', return_train_score=False)
grid_search = grid_knn.fit(X_train,y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy of K-Nearest Neighbor Model: {:.2f} %".format(best_accuracy*100))
print("Best Parameters of K-Nearest Neighbor Model:", best_parameters)
# make predictions on test data 
grid_predictions = grid_knn.predict(X_test) 
test_accuracy=accuracy_score(y_test,grid_predictions)*100
print("Accuracy for K-Nearest Neighbor testing dataset with tuning is : {:.2f}%".format(test_accuracy) )

Best Accuracy of K-Nearest Neighbor Model: 91.27 %
Best Parameters of K-Nearest Neighbor Model: {'n_neighbors': 6}
Accuracy for K-Nearest Neighbor testing dataset with tuning is : 91.19%


### **Gaussian Naive Bayes with GridSearchCV**

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
clf4 = GaussianNB()
parameters_4 = {
    'var_smoothing': (0,1e-9,1e-7, 1e-5), 
                   }
# with GridSearch
grid_search_NB = GridSearchCV(
    estimator=clf4,
    param_grid=parameters_4,
    scoring = 'accuracy',
    n_jobs = -1,
    cv = 5
)
grid_search=grid_search_NB.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy of Naive Bayes Model: {:.2f} %".format(best_accuracy*100))
print("Best Parameters of Naive Bayes Model:", best_parameters)
# make predictions on test data 
grid_predictions = grid_search_NB.predict(X_test) 
test_accuracy=accuracy_score(y_test,grid_predictions)*100
print("Accuracy for Naive Bayes testing dataset with tuning is : {:.2f}%".format(test_accuracy) )


Best Accuracy of Naive Bayes Model: 74.91 %
Best Parameters of Naive Bayes Model: {'var_smoothing': 1e-05}
Accuracy for Naive Bayes testing dataset with tuning is : 74.88%


### **Random Forest with GridSearchCV**

In [12]:
param_grid = {
    'n_estimators': [200, 700],
    'max_features': ['auto', 'sqrt', 'log2']
}
CV_rfc = GridSearchCV(estimator=clf6,param_grid=param_grid, cv= 5,scoring='accuracy')
CV_rfc.fit(X_train, y_train)
print("tuned hyperparameters :(best parameters) ",CV_rfc.best_params_)
print("Best accuracy for Random Forest Model :",CV_rfc.best_score_*100)
# make predictions on test data 
grid_predictions = CV_rfc.predict(X_test) 
test_accuracy=accuracy_score(y_test,grid_predictions)*100
print("Accuracy for Random Forest testing dataset with tuning is : {:.2f}%".format(test_accuracy) )

tuned hyperparameters :(best parameters)  {'max_features': 'auto', 'n_estimators': 700}
Best accuracy for Random Forest Model : 90.5859123934386
Accuracy for Random Forest testing dataset with tuning is : 90.44%


### **Kernel SVM with GridSearchCV**

In [13]:
# Importing the dataset
dataset = pd.read_csv('../input/social-network-ads/Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, -1].values
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Training the Kernel SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[64  4]
 [ 3 29]]


In [14]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy of Kernel SVM Model: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Accuracy of Kernel SVM Model: 90.00 %
Standard Deviation: 6.83 %
Best Accuracy: 91.00 %
Best Parameters: {'C': 1, 'gamma': 0.7, 'kernel': 'rbf'}


### **Linear Discriminant Analysis**

In [15]:
df2 = pd.read_csv('../input/uci-wine-dataset/wine.data', header = None)
df2.columns = ['Customer_Segment', 
                 'Alcohol', 
                 'Malic_Acid', 
                 'Ash', 'Ash_Alcanity', 
                 'Magnesium', 
                 'Total_Phenols', 
                 'Flavanoids', 
                 'Nonflavanoid_Phenols', 
                 'Proanthocyanins', 
                 'Color_Intensity', 
                 'Hue', 'OD280', 
                 'Proline']

In [16]:
from sklearn.model_selection import train_test_split
X = df2.iloc[:, 1:].values
y = df2.iloc[:, 0].values
#X = df.drop('HeartDisease',axis=1)
#y = df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X.shape

(178, 13)

In [18]:
#Default LDA model without any tuning - base metric
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda_default = LDA()
X_train_lda = lda_default.fit_transform(X_train, y_train)
X_test_lda = lda_default.transform(X_test)
y_pred_default =lda_default.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
print('Accuracy of LDA Default Model is ', accuracy_score(y_test, y_pred_default))
print('\n','Confusion Matrix of LDA Default Model:' '\n', confusion_matrix(y_test, y_pred_default))
print('\n', '\n','Classification Report for LDA Default Model:' '\n',classification_report(y_test, y_pred_default))

Accuracy of LDA Default Model is  0.9722222222222222

 Confusion Matrix of LDA Default Model:
 [[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]

 
 Classification Report for LDA Default Model:
               precision    recall  f1-score   support

           1       0.93      1.00      0.97        14
           2       1.00      0.94      0.97        16
           3       1.00      1.00      1.00         6

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36



#### **Parameter tuning with GridSearchCV - Method 1 (LDA  - lsqr & eigen)**

In [20]:
lda_1 = LDA(shrinkage='auto')
parameters_1 = {
    'solver': ('lsqr','eigen'),  #note svd does not run with shrinkage and models using it will be tuned separately
    'n_components': (0,1,2),
                   }


# with GridSearch
from sklearn.model_selection import GridSearchCV
grid_search_lda_1 = GridSearchCV(
    estimator=lda_1,
    param_grid=parameters_1,
    scoring = 'accuracy',
    n_jobs = -1,
    cv = 5
)
lda_1=grid_search_lda_1.fit(X_train, y_train)
y_pred_ldaTuned =lda_1.predict(X_test)
print('Accuracy of LDA Tuned Model is ', accuracy_score(y_test, y_pred_ldaTuned))
print('\n','Confusion Matrix of LDA Tuned Model:' '\n', confusion_matrix(y_test, y_pred_ldaTuned))
print('\n', '\n','Classification Report for LDA Tuned Model:' '\n',classification_report(y_test, y_pred_ldaTuned))

best_accuracy = lda_1.best_score_
best_parameters = lda_1.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Accuracy of LDA Tuned Model is  1.0

 Confusion Matrix of LDA Tuned Model:
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]

 
 Classification Report for LDA Tuned Model:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

Best Accuracy: 96.53 %
Best Parameters: {'n_components': 0, 'solver': 'lsqr'}


#### **Parameter tuning with GridSearchCV - Method 2 (LDA  - svd)**

In [21]:
lda_2 = LDA(solver='svd')#note svd does not run with shrinkage and models using it will be tuned separately 
parameters_2 = {
    'n_components': (0,1, 2),
    'store_covariance' :(True, False),
                       }
# with GridSearch
from sklearn.model_selection import GridSearchCV
grid_search_lda_2 = GridSearchCV(
    estimator=lda_2,
    param_grid=parameters_2,
    scoring = 'accuracy',
    n_jobs = -1,
    cv = 5
)
lda_2=grid_search_lda_2.fit(X_train, y_train)
y_pred_ldaTuned =lda_2.predict(X_test)
print('Accuracy of LDA Tuned Model is ', accuracy_score(y_test, y_pred_ldaTuned))
print('\n','Confusion Matrix of LDA Tuned Model:' '\n', confusion_matrix(y_test, y_pred_ldaTuned))
print('\n', '\n','Classification Report for LDA Tuned Model:' '\n',classification_report(y_test, y_pred_ldaTuned))

best_accuracy = lda_2.best_score_
best_parameters = lda_2.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Accuracy of LDA Tuned Model is  0.9722222222222222

 Confusion Matrix of LDA Tuned Model:
 [[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]

 
 Classification Report for LDA Tuned Model:
               precision    recall  f1-score   support

           1       0.93      1.00      0.97        14
           2       1.00      0.94      0.97        16
           3       1.00      1.00      1.00         6

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36

Best Accuracy: 97.93 %
Best Parameters: {'n_components': 0, 'store_covariance': True}


### **Quadratic Discriminant Analysis**

#### **QDA Without any tuning**

In [22]:
#Implementing QDA with Scikit-Learn
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
qda_default = QDA()
qda_default.fit(X_train, y_train)
y_pred_default =qda_default.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
print('Accuracy of QDA Default Model is ', accuracy_score(y_test, y_pred_default))
print('\n','Confusion Matrix of QDA Default Model:' '\n', confusion_matrix(y_test, y_pred_default))
print('\n', '\n','Classification Report for QDA Default Model:' '\n',classification_report(y_test, y_pred_default))

Accuracy of QDA Default Model is  1.0

 Confusion Matrix of QDA Default Model:
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]

 
 Classification Report for QDA Default Model:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



#### **Parameter tuning with GridSearchCV**

In [23]:
from sklearn.model_selection import GridSearchCV
qda1 = QDA()
parameters = {
    'reg_param': (0.00001, 0.0001, 0.001,0.01, 0.1), 
    'store_covariance': (True, False),
    'tol': (0.0001, 0.001,0.01, 0.1), 
                   }
# with GridSearch
grid_search_qda = GridSearchCV(
    estimator=qda1,
    param_grid=parameters,
    scoring = 'accuracy',
    n_jobs = -1,
    cv = 5
)
qda_1=grid_search_qda.fit(X_train, y_train)
y_pred_qda =qda_1.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
print('Accuracy of QDA Tuned Model is ', accuracy_score(y_test, y_pred_qda))
print('\n','Confusion Matrix of QDA Tuned Model:' '\n', confusion_matrix(y_test, y_pred_qda))
print('\n', '\n','Classification Report for QDA Tuned Model:' '\n',classification_report(y_test, y_pred_qda))
best_accuracy = qda_1.best_score_
best_parameters = qda_1.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

Accuracy of QDA Tuned Model is  1.0

 Confusion Matrix of QDA Tuned Model:
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]

 
 Classification Report for QDA Tuned Model:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

Best Accuracy: 98.57 %
Best Parameters: {'reg_param': 1e-05, 'store_covariance': True, 'tol': 0.0001}
